/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA

/**
 * ContentPermission generated by hbm2java
 */
public class ContentPermission implements java.io.Serializable {

   public enum Rights {

      view, history, comment, edit, add, delete, html, programming, admin
   };
   private Integer id;
   private Integer content;
   private User user;
   private Group group;
   private Boolean view = true;
   private Boolean history = true;
   private Boolean comment = false;
   private Boolean edit = false;
   private Boolean delete = false;
   private Boolean add = false;
   private Boolean html = false;
   private Boolean programming = false;
   private Boolean admin = false;

   public ContentPermission() {
   }

   public Integer getId() {
      return this.id;
   }

   public void setId(Integer id) {
      this.id = id;
   }

   public Integer getContent() {
      return this.content;
   }

   public void setContent(Integer content) {
      this.content = content;
   }

   public User getUser() {
      return this.user;
   }

   public void setUser(User user) {
      this.user = user;
   }

   /**
    * @return the group
    */
   public Group getGroup() {
      return group;
   }

   /**
    * @param group the group to set
    */
   public void setGroup(Group group) {
      this.group = group;
   }

   public Boolean has(Rights perm) {
      switch (perm) {
         case view:
            return view;
         case history:
            return history;
         case edit:
            return edit;
         case comment:
            return comment;
         case delete:
            return delete;
         case add:
            return add;
         case html:
            return html;
         case programming:
            return programming;
         case admin:
            return admin;
         default:
            throw new IllegalArgumentException("Unknown permission " + perm);
      }

   }

   /**
    * @return the view
    */
   public Boolean getView() {
      return view;
   }

   /**
    * @param view the view to set
    */
   public void setView(Boolean view) {
      this.view = view;
   }


   /**
    * @return the history
    */
   public Boolean getHistory() {
      return history;
   }

   /**
    * @param history the history to set
    */
   public void setHistory(Boolean history) {
      this.history = history;
   }

   /**
    * @return the edit
    */
   public Boolean getEdit() {
      return edit;
   }

   /**
    * @param edit the edit to set
    */
   public void setEdit(Boolean edit) {
      this.edit = edit;
   }

   /**
    * @return the admin
    */
   public Boolean getAdmin() {
      return admin;
   }

   /**
    * @param admin the admin to set
    */
   public void setAdmin(Boolean admin) {
      this.admin = admin;
   }

   /**
    * @return the delete
    */
   public Boolean getDelete() {
      return delete;
   }

   /**
    * @param delete the delete to set
    */
   public void setDelete(Boolean delete) {
      this.delete = delete;
   }

   /**
    * @return the add
    */
   public Boolean getAdd() {
      return add;
   }

   /**
    * @param add the add to set
    */
   public void setAdd(Boolean add) {
      this.add = add;
   }

   /**
    * @return the comment
    */
   public Boolean getComment() {
      return comment;
   }

   /**
    * @param comment the comment to set
    */
   public void setComment(Boolean comment) {
      this.comment = comment;
   }

   /**
    * @return the html
    */
   public Boolean getHtml() {
      return html;
   }

   /**
    * @param html the html to set
    */
   public void setHtml(Boolean html) {
      this.html = html;
   }

   /**
    * @return the programming
    */
   public Boolean getProgramming() {
      return programming;
   }

   /**
    * @param programming the programming to set
    */
   public void setProgramming(Boolean programming) {
      this.programming = programming;
   }
}


