/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * ContentHistory generated by hbm2java
 */
public class ContentHistory implements java.io.Serializable {

   private Integer id;
   private Integer content;
   private Integer version = 0;
   private User user;
   private Date modifiedDate;
   private String changeType;
   private String changeDiff;
   private String changeReason;

   public ContentHistory() {
   }

   public ContentHistory(Integer content, Integer version, User user, Date modifiedDate, String changeType, String changeDiff, String changeReason) {
      this.content = content;
      this.version = version;
      this.user = user;
      this.modifiedDate = modifiedDate;
      this.changeType = changeType;
      this.changeDiff = changeDiff;
      this.changeReason = changeReason;
   }

   public Integer getId() {
      return this.id;
   }

   public void setId(Integer id) {
      this.id = id;
   }

   public Integer getContent() {
      return this.content;
   }

   public void setContent(Integer content) {
      this.content = content;
   }

   public User getUser() {
      return this.user;
   }

   public void setUser(User user) {
      this.user = user;
   }

   public Date getModifiedDate() {
      return this.modifiedDate;
   }

   public void setModifiedDate(Date modifiedDate) {
      this.modifiedDate = modifiedDate;
   }

   public String getChangeType() {
      return this.changeType;
   }

   public void setChangeType(String changeType) {
      this.changeType = changeType;
   }

   public String getChangeDiff() {
      return this.changeDiff;
   }

   public void setChangeDiff(String changeDiff) {
      this.changeDiff = changeDiff;
   }

   /**
    * @return the version
    */
   public Integer getVersion() {
      return version;
   }

   /**
    * @param version the version to set
    */
   public void setVersion(Integer version) {
      this.version = version;
   }

   /**
    * @return the changeReason
    */
   public String getChangeReason() {
      return changeReason;
   }

   /**
    * @param changeReason the changeReason to set
    */
   public void setChangeReason(String changeReason) {
      this.changeReason = changeReason;
   }
}


