/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;


import com.quaap.yacm.render.MarkupType;
import java.util.Date;

/**
 * Content generated by hbm2java
 */
public class Content implements java.io.Serializable {

   private Integer id;
   private Content parent;
   private String path;
   private Integer version = 0;
   private Integer state = ContentState.published.getId();
   private Boolean isblob = false;
   private String contenttype;
   private Integer markuptype = MarkupType.wiki.getId();
   private String title;
   private Integer length;
   private String content;
   private BinContent binContent;
   private User creator;
   private User lastModifier;
   private Date createDate;
   private Date modifiedDate;
   private String changeReason;

   public static void copyContent(Content src, Content dest) {
      dest.setParent(src.getParent());
      dest.setPath(src.getPath());
      dest.setTitle(src.getTitle());
      dest.setVersion(src.getVersion());
      dest.setContentState(src.getContentState());
      dest.setBlob(src.isBlob());
      dest.setContenttype(src.getContenttype());
      dest.setMarkuptype(src.getMarkuptype());
      dest.setLength(src.getLength());
      dest.setContent(src.getContent());
      dest.setBinContent(src.getBinContent());
      dest.setCreator(src.getCreator());
      dest.setLastModifier(src.getLastModifier());
      dest.setCreateDate(src.getCreateDate());
      dest.setModifiedDate(src.getModifiedDate());
      dest.setId(src.getId());
      dest.setChangeReason(src.getChangeReason());
   }

   public Content() {
   }

//   public Content(String path, Integer version, Boolean isblob, BinContent binContent, String contenttype, MarkupType markuptype, String title, String content, User creator, User lastModifier, Date createDate, Date modifiedDate) {
//      this.path = path;
//      this.version = version;
//      this.isblob = isblob;
//      this.contenttype = contenttype;
//      setMarkupType(markuptype);
//      this.title = title;
//      this.content = content;
//      this.binContent = binContent;
//      this.creator = creator;
//      this.lastModifier = lastModifier;
//      this.createDate = createDate;
//      this.modifiedDate = modifiedDate;
//   }

   public Content(Content src) {
      copyContent(src, this);
   }

   public Integer getId() {
      return this.id;
   }

   public void setId(Integer id) {
      this.id = id;
   }

   public String getPath() {
      return this.path;
   }

   public void setPath(String path) {
      this.path = path;
   }

   public Boolean isBlob() {
      return this.isblob;
   }

   public void setBlob(Boolean isblob) {
      this.isblob = isblob;
   }

   public String getContent() {
      return this.content;
   }

   public void setContent(String content) {
      this.content = content;
      if (this.content!=null) {
         this.length = this.content.length();
      }
   }

   public BinContent getBinContent() {
      return this.binContent;
   }

   public void setBinContent(BinContent binContent) {
      this.binContent = binContent;
   }

   public User getCreator() {
      return this.creator;
   }

   public void setCreator(User creator) {
      this.creator = creator;
   }

   public User getLastModifier() {
      return this.lastModifier;
   }

   public void setLastModifier(User lastModifier) {
      this.lastModifier = lastModifier;
   }

   public Date getCreateDate() {
      return this.createDate;
   }

   public void setCreateDate(Date createDate) {
      this.createDate = createDate;
   }

   public Date getModifiedDate() {
      return this.modifiedDate;
   }

   public void setModifiedDate(Date modifiedDate) {
      this.modifiedDate = modifiedDate;
   }

   /**
    * @return the title
    */
   public String getTitle() {
      return title;
   }

   /**
    * @param title the title to set
    */
   public void setTitle(String title) {
      this.title = title;
   }

   /**
    * @return the version
    */
   public Integer getVersion() {
      return version;
   }

   /**
    * @param version the version to set
    */
   public void setVersion(Integer version) {
      this.version = version;
   }

   /**
    * @return the changeReason
    */
   public String getChangeReason() {
      return changeReason;
   }

   /**
    * @param changeReason the changeReason to set
    */
   public void setChangeReason(String changeReason) {
      this.changeReason = changeReason;
   }

   /**
    * @return the contenttype
    */
   public String getContenttype() {
      return contenttype;
   }

   /**
    * @param contenttype the contenttype to set
    */
   public void setContenttype(String contenttype) {
      this.contenttype = contenttype;
   }

   /**
    * @return the markuptype
    */
   private Integer getMarkuptype() {
      return markuptype;
   }

   /**
    * @param markuptype the markuptype to set
    */
   private void setMarkuptype(Integer markuptype) {
      this.markuptype = markuptype;
   }

   /**
    * @return the markuptype
    */
   public MarkupType getMarkupType() {
      return MarkupType.getMarkupType(markuptype);
   }

   /**
    * @param markuptype the markuptype to set
    */
   public void setMarkupType(MarkupType markuptype) {
      this.markuptype = markuptype.getId();
   }

   /**
    * @return the state
    */
   private Integer getState() {
      return state;
   }

   /**
    * @param state the state to set
    */
   private void setState(Integer state) {
      this.state = state;
   }

   public void setContentState(ContentState state) {
      setState(state.getId());
   }

   public ContentState getContentState() {
      return ContentState.getContentState(this.state);
   }

   /**
    * @return the parent
    */
   public Content getParent() {
      return parent;
   }

   /**
    * @param parent the parent to set
    */
   public void setParent(Content parent) {
      this.parent = parent;
   }

   /**
    * @return the length
    */
   public Integer getLength() {
      return length;
   }

   /**
    * @param length the length to set
    */
   public void setLength(Integer length) {
      this.length = length;
   }
}


