/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;

/**
 * Metadata generated by hbm2java
 */
public class Metadata implements java.io.Serializable {

   private Integer id;
   private Integer content;
   private Integer type;
   private String name;
   private String value;
  // private Integer submitter;
  // private Date createDate;
  // private Date modifiedDate;

   public enum DataType { 
      String(1), Integer(2), Date(3);

      public static DataType getDataType(int id) {
         for (DataType t: DataType.values()) {
            if (t.id == id) return t;
         }
         return null;
      }

      private int id;
      private DataType(int id) {
         this.id = id;
      }

      public int getId() {
         return id;
      }
   };

   public Metadata() {
   }

   public Integer getId() {
      return this.id;
   }

   public void setId(Integer id) {
      this.id = id;
   }

   public Integer getContent() {
      return this.content;
   }

   public void setContent(Integer content) {
      this.content = content;
   }

   public String getName() {
      return this.name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getValue() {
      return this.value;
   }

   public void setValue(String value) {
      this.value = value;
   }

//   public Integer getSubmitter() {
//      return this.submitter;
//   }
//
//   public void setSubmitter(Integer submitter) {
//      this.submitter = submitter;
//   }
//
//   public Date getCreateDate() {
//      return this.createDate;
//   }
//
//   public void setCreateDate(Date createDate) {
//      this.createDate = createDate;
//   }
//
//   public Date getModifiedDate() {
//      return this.modifiedDate;
//   }
//
//   public void setModifiedDate(Date modifiedDate) {
//      this.modifiedDate = modifiedDate;
//   }


   public void setDataType(DataType type) {
      this.type = type.getId();
   }

   public DataType getDataType() {
      return DataType.getDataType(type);
   }

   /**
    * @return the type
    */
   private Integer getType() {
      return type;
   }

   /**
    * @param type the type to set
    */
   private void setType(Integer type) {
      this.type = type;
   }
}


