/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

   private Integer id;
   private String username;
   private String name;
   private String info;
   private Date createDate;
   private Date modifiedDate;
   private Set<Group> groups;

   public User() {
   }

   public Integer getId() {
      return this.id;
   }

   public void setId(Integer id) {
      this.id = id;
   }

   public String getUsername() {
      return this.username;
   }

   public void setUsername(String username) {
      this.username = username;
   }

   public String getName() {
      return this.name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getInfo() {
      return this.info;
   }

   public void setInfo(String info) {
      this.info = info;
   }

   public Date getCreateDate() {
      return this.createDate;
   }

   public void setCreateDate(Date createDate) {
      this.createDate = createDate;
   }

   public Date getModifiedDate() {
      return this.modifiedDate;
   }

   public void setModifiedDate(Date modifiedDate) {
      this.modifiedDate = modifiedDate;
   }

   public Set<Group> getGroups() {
      if (this.groups==null) {
         this.groups = new HashSet<Group>();
      }
      return this.groups;
   }

   public void setGroups(Set<Group> groups) {
      this.groups = groups;
   }

   public void addGroup(Group group) {
      if (this.groups==null) {
         this.groups = new HashSet<Group>();
      }
      this.groups.add(group);
   }

   public boolean isInGroup(final String groupname) {
      if (getGroups()==null) {
         return false;
      }
      for (Group group : getGroups()) {
         if (group.getGroupname().equals(groupname)) {
            return true;
         }
      }
      return false;
   }
}


