/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.storage.bean;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * ContentHistory generated by hbm2java
 */
public class Visit implements java.io.Serializable {

   private Long id;
   private String action;
   private String path;
   private String querystr;
   private Date accessDate;
   private Integer user;
   private String ip;
   private String referrer;
   private String browser;
   private String error;

   public Visit() {
   }

   public Long getId() {
      return this.id;
   }

   public void setId(Long id) {
      this.id = id;
   }


   public Integer getUser() {
      return this.user;
   }

   public void setUser(Integer user) {
      this.user = user;
   }

   public Date getAccessDate() {
      return this.accessDate;
   }

   public void setAccessDate(Date accessDate) {
      this.accessDate = accessDate;
   }

   /**
    * @return the action
    */
   public String getAction() {
      return action;
   }

   /**
    * @param action the action to set
    */
   public void setAction(String action) {
      this.action = action;
   }

   /**
    * @return the querystr
    */
   public String getQuerystr() {
      return querystr;
   }

   /**
    * @param querystr the querystr to set
    */
   public void setQuerystr(String querystr) {
      this.querystr = querystr;
   }

   /**
    * @return the ip
    */
   public String getIp() {
      return ip;
   }

   /**
    * @param ip the ip to set
    */
   public void setIp(String ip) {
      this.ip = ip;
   }

   /**
    * @return the referrer
    */
   public String getReferrer() {
      return referrer;
   }

   /**
    * @param referrer the referrer to set
    */
   public void setReferrer(String referrer) {
      this.referrer = referrer;
   }

   /**
    * @return the browser
    */
   public String getBrowser() {
      return browser;
   }

   /**
    * @param browser the browser to set
    */
   public void setBrowser(String browser) {
      this.browser = browser;
   }

   /**
    * @return the error
    */
   public String getError() {
      return error;
   }

   /**
    * @param error the error to set
    */
   public void setError(String error) {
      this.error = error;
   }

   /**
    * @return the path
    */
   public String getPath() {
      return path;
   }

   /**
    * @param path the path to set
    */
   public void setPath(String path) {
      this.path = path;
   }

}


