/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.api.beans;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA

import com.quaap.yacm.storage.bean.ContentHistory;
import java.util.Date;

/**
 * ContentHistory generated by hbm2java
 */
public class SafeContentHistory implements java.io.Serializable {

   final private ContentHistory unsafech;


   public SafeContentHistory(final ContentHistory ch) {
      unsafech = ch;
   }


   public Integer getId() {
      return unsafech.getId();
   }


   public Integer getContent() {
      return unsafech.getContent();
   }


   public SafeUser getUser() {
      return new SafeUser(unsafech.getUser());
   }


   public Date getModifiedDate() {
      return unsafech.getModifiedDate();
   }


   public String getChangeType() {
      return unsafech.getChangeType();
   }


   public String getChangeDiff() {
      return unsafech.getChangeDiff();
   }


   /**
    * @return the version
    */
   public Integer getVersion() {
      return unsafech.getVersion();
   }


   /**
    * @return the changeReason
    */
   public String getChangeReason() {
      return unsafech.getChangeReason();
   }

}


