/*
 *  Copyright (c) 2009 Thomas Kliethermes, thamus@kc.rr.com
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.quaap.yacm.api.beans;
// Generated Feb 14, 2009 10:05:10 PM by Hibernate Tools 3.2.1.GA

import com.quaap.yacm.render.MarkupType;
import com.quaap.yacm.storage.bean.Content;
//import java.sql.Blob;
import com.quaap.yacm.storage.bean.ContentState;
import java.util.Date;

/**
 * Content generated by hbm2java
 */
public class SafeContent implements java.io.Serializable {

   final private Content unsafecontent;

   public SafeContent(final Content c) {
      unsafecontent = c;
   }

   public Integer getId() {
      return unsafecontent.getId();
   }

   public Content getParent() {
      return unsafecontent.getParent();
   }

   public String getPath() {
      return unsafecontent.getPath();
   }

   public Boolean isBlob() {
      return unsafecontent.isBlob();
   }

   public String getContent() {
      return unsafecontent.getContent();
   }

//   public Blob getBinContent() {
//      return unsafecontent.getBinContent();
//   }

   public SafeUser getCreator() {
      return new SafeUser(unsafecontent.getCreator());
   }

   public SafeUser getLastModifier() {
      return new SafeUser(unsafecontent.getLastModifier());
   }

   public Date getCreateDate() {
      return unsafecontent.getCreateDate();
   }

   public Date getModifiedDate() {
      return unsafecontent.getModifiedDate();
   }

   /**
    * @return the title
    */
   public String getTitle() {
      return unsafecontent.getTitle();
   }

   /**
    * @return the version
    */
   public Integer getVersion() {
      return unsafecontent.getVersion();
   }

   /**
    * @return the changeReason
    */
   public String getChangeReason() {
      return unsafecontent.getChangeReason();
   }

   /**
    * @return the contenttype
    */
   public String getContenttype() {
      return unsafecontent.getContenttype();
   }

   public MarkupType getMarkupType() {
      return unsafecontent.getMarkupType();
   }


   public ContentState getContentState() {
      return unsafecontent.getContentState();
   }


}


